library(survivoR)
library(arrow)

# Output directories
parquet_dir <- "../data/"  # change as needed
table_names_py <- "../survivorpy/table_names.py"

# Create output directory if it doesn't exist
if (!dir.exists(parquet_dir)) {
  dir.create(parquet_dir, recursive = TRUE)
}

# Get dataset names from the package
dataset_names <- data(package = "survivoR")$results[, "Item"]

# Initialize a vector to collect names successfully written
written_tables <- c()

for (name in dataset_names) {
  df <- tryCatch(get(name, envir = asNamespace("survivoR")),
                 error = function(e) NULL)
  
  if (!is.null(df) && is.data.frame(df)) {
    arrow::write_parquet(df, file.path(parquet_dir, paste0(name, ".parquet")))
    written_tables <- c(written_tables, name)
  } else {
    message(sprintf("Skipping %s: not a valid dataframe", name))
  }
}

# Write the Python table_names.py file
py_lines <- c(
  "# This file is generated by convert_survivor_to_parquet.R",
  "",
  "TABLE_NAMES = ["
)

py_lines <- c(py_lines, paste0("    '", written_tables, "',"))
py_lines <- c(py_lines, "]", "")

writeLines(py_lines, table_names_py)

cat("Done! Wrote", length(written_tables), "parquet files and table_names.py\n")
