name: Upload Survivor Data to S3

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
  #
  # schedule:
  #   - cron: '0 8 * * 6'  # Every Saturday at 1am MST (8am UTC)

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            r-base \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \
            libarrow-dev \
            cmake \
            make \
            g++

      - name: Set up R user library
        run: |
          mkdir -p ~/.R/library
          echo 'R_LIBS_USER="~/.R/library"' >> ~/.Renviron

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.R/library
          key: ${{ runner.os }}-r-library-${{ hashFiles('**/scripts/convert_survivor_to_parquet.R') }}
          restore-keys: |
            ${{ runner.os }}-r-library-

      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c("arrow", "aws.s3", "jsonlite", "remotes"), repos="https://cloud.r-project.org", lib="~/.R/library")'
          Rscript -e 'remotes::install_github("doehm/survivoR", lib="~/.R/library")'

      - name: Run R script to upload data to S3
        run: |
          Rscript -e '.libPaths("~/.R/library"); source("scripts/convert_survivor_to_parquet.R")'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
