name: Upload Survivor Data to S3

on:
  workflow_dispatch:

  # push:
  #   branches:
  #     - main
  #
  # schedule:
  #   - cron: '0 8 * * 6'  # Every Saturday at 1am MST (8am UTC)

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run R script to upload data
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base
          Rscript scripts/convert_survivor_to_parquet.R
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

